name: Build APK

on:
  push:
    branches:
      - main

env:
  ANDROID_HOME: /usr/local/lib/android/sdk
  ANDROID_NDK_VERSION: 25.2.9519653

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for proper version detection

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-dev \
            build-essential \
            openjdk-17-jdk \
            zlib1g-dev \
            libncurses5-dev \
            libgdbm-dev \
            libnss3-dev \
            libssl-dev \
            libsqlite3-dev \
            libreadline-dev \
            libffi-dev \
            libbz2-dev \
            unzip \
            zip \
            wget \
            git \
            cmake

          sudo update-java-alternatives --set java-1.17.0-openjdk-amd64
          echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $GITHUB_ENV

      - name: Set up Android SDK
        run: |
          mkdir -p $ANDROID_HOME
          cd $ANDROID_HOME
          
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip -q commandlinetools-linux-*.zip
          rm commandlinetools-linux-*.zip
          
          mkdir -p cmdline-tools/latest
          mv cmdline-tools/* cmdline-tools/latest/ || true
          mv lib/ cmdline-tools/latest/ || true
          mv bin/ cmdline-tools/latest/ || true
          mv NOTICE.txt cmdline-tools/latest/ || true
          mv source.properties cmdline-tools/latest/ || true
          
          echo "$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/34.0.0" >> $GITHUB_PATH

      - name: Install Android components
        run: |
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg
          
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses >/dev/null 2>&1
          
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager \
            "platform-tools" \
            "build-tools;34.0.0" \
            "platforms;android-34" \
            "cmake;3.22.1"
            
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "ndk;$ANDROID_NDK_VERSION"
          
          echo "ANDROID_NDK_HOME=$ANDROID_HOME/ndk/$ANDROID_NDK_VERSION" >> $GITHUB_ENV

      - name: Install Buildozer and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir cython==0.29.36 buildozer python-for-android

      - name: Initialize Buildozer environment
        run: |
          # First run to initialize p4a
          buildozer init || true
          buildozer android update || true
          
          # Proper spec configuration
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi
          
          cat << EOF >> buildozer.spec
[buildozer]
log_level = 2

[android]
android.ndk_path = $ANDROID_NDK_HOME
android.sdk_path = $ANDROID_HOME
android.build_tools_version = 34.0.0
android.api = 34
android.minapi = 21
android.ndk_api = 21
android.arch = arm64-v8a
EOF

      - name: Build APK
        run: |
          export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/34.0.0
          export ANDROID_HOME=$ANDROID_HOME
          export ANDROID_NDK_HOME=$ANDROID_NDK_HOME
          
          # Clean and build with full logging
          buildozer android clean 2>&1 | tee clean.log || true
          buildozer -v android debug 2>&1 | tee build.log
          
          if [ ! -f bin/*.apk ]; then
            echo "Build failed! Check logs above"
            exit 1
          fi

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: bin/*.apk
          if-no-files-found: error
          retention-days: 5

      - name: Upload build logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-logs
          path: |
            build.log
            clean.log
            .buildozer/android/platform/build-*/dists/*/build/outputs/apk/debug/*.log
          retention-days: 5
