name: Build Android APK

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install Android SDK and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git zip unzip \
          openjdk-11-jdk \
          python3-pip \
          autoconf libtool pkg-config \
          zlib1g-dev libncurses-dev \
          cmake libffi-dev libssl-dev \
          android-sdk
        
        # Setup Android SDK
        mkdir -p ~/android-sdk
        cd ~/android-sdk
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip commandlinetools-linux-9477386_latest.zip
        rm commandlinetools-linux-9477386_latest.zip
        mkdir cmdline-tools
        mv tools cmdline-tools/latest
        
        # Accept all licenses first
        yes | ~/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
        
        # Install specific versions that work well with Buildozer
        ~/android-sdk/cmdline-tools/latest/bin/sdkmanager \
          "platform-tools" \
          "platforms;android-31" \
          "build-tools;31.0.0" \
          "ndk;23.1.7779620"
        
        # Setup environment
        echo "export ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
        echo "export ANDROID_NDK_HOME=$HOME/android-sdk/ndk/23.1.7779620" >> $GITHUB_ENV
        echo "export PATH=$PATH:$HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools" >> $GITHUB_ENV
        
        pip install buildozer==1.5.0 cython virtualenv
        
    - name: Update buildozer.spec
      run: |
        # Clean up spec file
        awk '!/android.allow_backup =/' buildozer.spec > temp && mv temp buildozer.spec
        awk '!/android.arch =/' buildozer.spec > temp && mv temp buildozer.spec
        
        # Add verified working configurations
        echo "android.allow_backup = True" >> buildozer.spec
        echo "android.archs = armeabi-v7a" >> buildozer.spec
        echo "android.sdk_path = $HOME/android-sdk" >> buildozer.spec
        echo "android.ndk_path = $HOME/android-sdk/ndk/23.1.7779620" >> buildozer.spec
        echo "android.accept_sdk_license = True" >> buildozer.spec
        echo "android.sdk_version = 31" >> buildozer.spec
        echo "android.build_tools_version = 31.0.0" >> buildozer.spec
        
    - name: Build APK
      run: |
        # Clean environment
        rm -rf .buildozer || true
        
        # Build with verbose output
        buildozer -v android debug
        
        # Verify build succeeded
        if [ ! -f bin/*.apk ]; then
          echo "Build failed! Showing logs:"
          cat .buildozer/android/platform/build-*/build.out
          exit 1
        fi
        
        ls -la bin/
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: calculator-app
        path: bin/*.apk
