name: Build Android APK

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git zip unzip \
          openjdk-11-jdk \
          python3-pip \
          autoconf libtool pkg-config \
          zlib1g-dev libncurses-dev \
          cmake libffi-dev libssl-dev
        
        # Install Android Command Line Tools
        mkdir -p ~/android-sdk/cmdline-tools/latest
        cd ~/android-sdk
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip -o commandlinetools-linux-9477386_latest.zip -d tmp
        rm commandlinetools-linux-9477386_latest.zip
        
        # Move files to correct location
        if [ -d "tmp/cmdline-tools" ]; then
          mv tmp/cmdline-tools/* cmdline-tools/latest/
        else
          mv tmp/* cmdline-tools/latest/
        fi
        rm -rf tmp
        
        # Verify installation
        if [ ! -f "cmdline-tools/latest/bin/sdkmanager" ]; then
          echo "Android SDK tools not properly installed!"
          ls -R cmdline-tools/
          exit 1
        fi
        
        # Accept licenses
        yes | ~/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
        
        # Install specific working versions
        ~/android-sdk/cmdline-tools/latest/bin/sdkmanager \
          "platform-tools" \
          "platforms;android-31" \
          "build-tools;31.0.0" \
          "ndk;23.1.7779620"
        
        # Install AIDL from Android SDK (now included in build-tools)
        # Also ensure PATH includes build-tools directory
        echo "PATH=$PATH:$HOME/android-sdk/build-tools/31.0.0" >> $GITHUB_ENV
        
        # Verify aidl is available
        if [ ! -f "$HOME/android-sdk/build-tools/31.0.0/aidl" ]; then
          echo "AIDL not found in build-tools!"
          ls -R $HOME/android-sdk/build-tools/31.0.0/
          exit 1
        fi
        
        pip install buildozer==1.5.0 cython virtualenv
        
    - name: Update buildozer.spec
      run: |
        # Clean and update buildozer.spec
        awk '!/android.allow_backup =/' buildozer.spec > temp && mv temp buildozer.spec
        awk '!/android.arch =/' buildozer.spec > temp && mv temp buildozer.spec
        
        echo "android.allow_backup = True" >> buildozer.spec
        echo "android.archs = armeabi-v7a" >> buildozer.spec
        echo "android.sdk_path = $HOME/android-sdk" >> buildozer.spec
        echo "android.ndk_path = $HOME/android-sdk/ndk/23.1.7779620" >> buildozer.spec
        echo "android.accept_sdk_license = True" >> buildozer.spec
        echo "android.sdk_version = 31" >> buildozer.spec
        echo "android.build_tools_version = 31.0.0" >> buildozer.spec
        echo "android.build_tools_dir = $HOME/android-sdk/build-tools/31.0.0" >> buildozer.spec
        
    - name: Build APK
      run: |
        rm -rf .buildozer || true
        
        # Verify tools
        which aidl || { 
          echo "AIDL not found in PATH! Trying build-tools directory..."
          if [ -f "$HOME/android-sdk/build-tools/31.0.0/aidl" ]; then
            echo "Found AIDL in build-tools, adding to PATH"
            export PATH=$PATH:$HOME/android-sdk/build-tools/31.0.0
          else
            echo "AIDL not found anywhere!"
            exit 1
          fi
        }
        
        which aapt || { echo "AAPT not found!"; exit 1; }
        
        buildozer -v android debug
        
        if [ ! -f bin/*.apk ]; then
          echo "Build failed! Showing logs:"
          cat .buildozer/android/platform/build-*/build.out
          exit 1
        fi
        
        ls -la bin/
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: calculator-app
        path: bin/*.apk
