      - name: Initialize Buildozer environment
        run: |
          # Initialize if file doesn't exist
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi
          
          # Update existing spec file without creating duplicates
          if grep -q "^\[buildozer\]" buildozer.spec; then
            # Update existing sections
            sed -i '/^\[buildozer\]/,/^\[/ s/^log_level = .*/log_level = 2/' buildozer.spec
            sed -i '/^\[android\]/,/^\[/ s/^android\.ndk_path = .*/android.ndk_path = $ANDROID_NDK_HOME/' buildozer.spec
            sed -i '/^\[android\]/,/^\[/ s/^android\.sdk_path = .*/android.sdk_path = $ANDROID_HOME/' buildozer.spec
            sed -i '/^\[android\]/,/^\[/ s/^android\.build_tools_version = .*/android.build_tools_version = 34.0.0/' buildozer.spec
            sed -i '/^\[android\]/,/^\[/ s/^android\.api = .*/android.api = 34/' buildozer.spec
            sed -i '/^\[android\]/,/^\[/ s/^android\.minapi = .*/android.minapi = 21/' buildozer.spec
            sed -i '/^\[android\]/,/^\[/ s/^android\.ndk_api = .*/android.ndk_api = 21/' buildozer.spec
            sed -i '/^\[android\]/,/^\[/ s/^android\.arch = .*/android.arch = arm64-v8a/' buildozer.spec
          else
            # Add sections if they don't exist
            echo -e "\n[buildozer]\nlog_level = 2\n\n[android]" >> buildozer.spec
            echo "android.ndk_path = $ANDROID_NDK_HOME" >> buildozer.spec
            echo "android.sdk_path = $ANDROID_HOME" >> buildozer.spec
            echo "android.build_tools_version = 34.0.0" >> buildozer.spec
            echo "android.api = 34" >> buildozer.spec
            echo "android.minapi = 21" >> buildozer.spec
            echo "android.ndk_api = 21" >> buildozer.spec
            echo "android.arch = arm64-v8a" >> buildozer.spec
          fi
          
          # Run update after configuration
          buildozer android update || true
