      - name: Initialize Buildozer environment
        run: |
          # Initialize fresh if no spec file exists
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi
          
          # Create a clean temporary spec file
          TEMP_SPEC=$(mktemp)
          
          # Process existing file or create new one
          {
            # Keep all existing content except our target sections
            if [ -f buildozer.spec ]; then
              awk '
              /^\[buildozer\]/ { in_buildozer=1; next }
              /^\[android\]/ { in_android=1; next }
              /^\[/ { in_buildozer=0; in_android=0 }
              in_buildozer || in_android { next }
              { print }
              ' buildozer.spec
            fi
          
            # Add our standardized configuration
            echo -e "\n[buildozer]\nlog_level = 2"
            echo -e "\n[android]"
            echo "android.ndk_path = $ANDROID_NDK_HOME"
            echo "android.sdk_path = $ANDROID_HOME"
            echo "android.build_tools_version = 34.0.0"
            echo "android.api = 34"
            echo "android.minapi = 21"
            echo "android.ndk_api = 21"
            echo "android.arch = arm64-v8a"
          } > "$TEMP_SPEC"
          
          # Replace original file
          mv "$TEMP_SPEC" buildozer.spec
          
          # Verify the configuration
          echo "=== Final buildozer.spec ==="
          cat buildozer.spec
          
          # Initialize the environment
          buildozer android update || true
