      - name: Create fresh buildozer.spec
        run: |
          # Create brand new spec file with our exact configuration
          cat << 'EOF' > buildozer.spec
[app]
title = MyApp
package.name = myapp
package.domain = org.test
source.dir = .
source.include_exts = py,png,jpg,kv,atlas
version = 0.1
requirements = python3,kivy
orientation = portrait
fullscreen = 0

[buildozer]
log_level = 2
warn_on_root = 1

[android]
android.ndk_path = $ANDROID_NDK_HOME
android.sdk_path = $ANDROID_HOME
android.build_tools_version = 34.0.0
android.api = 34
android.minapi = 21
android.ndk_api = 21
android.arch = arm64-v8a
android.permissions = INTERNET
EOF
          # Substitute environment variables
          sed -i "s|\$ANDROID_NDK_HOME|$ANDROID_NDK_HOME|g" buildozer.spec
          sed -i "s|\$ANDROID_HOME|$ANDROID_HOME|g" buildozer.spec
          echo "=== buildozer.spec ==="
          cat buildozer.spec
