name: "Build APK"  # Double-quoted string to ensure proper YAML parsing

on:
  push:
    branches: 
      - main

env:
  ANDROID_HOME: "/usr/local/lib/android/sdk"
  ANDROID_NDK_VERSION: "25.2.9519653"  # Quoted version string

jobs:
  build:
    runs-on: "ubuntu-latest"  # Quoted runner name
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v4"  # Quoted action with version

      - name: "Set up Python 3.9"
        uses: "actions/setup-python@v4"
        with:
          python-version: "3.9"  # Quoted version number

      # ... [rest of your workflow remains exactly the same] ...
