      - name: Initialize Buildozer environment
        run: |
          # Completely remove any existing spec file to start fresh
          rm -f buildozer.spec
          
          # Initialize a brand new spec file
          buildozer init
          
          # Create a clean new spec file with our exact configuration
          cat << 'EOF' > buildozer.spec
[app]
title = My Application
package.name = myapp
package.domain = org.example
source.dir = .
source.include_exts = py,png,jpg,kv,atlas
version = 0.1
requirements = python3,kivy
orientation = portrait
fullscreen = 0

[buildozer]
log_level = 2
warn_on_root = 1

[android]
android.ndk_path = $ANDROID_NDK_HOME
android.sdk_path = $ANDROID_HOME
android.build_tools_version = 34.0.0
android.api = 34
android.minapi = 21
android.ndk_api = 21
android.arch = arm64-v8a
android.permissions = INTERNET
android.allow_backup = True
android.accept_sdk_license = True
EOF

          # Replace environment variables in the spec file
          sed -i "s|\$ANDROID_NDK_HOME|$ANDROID_NDK_HOME|g" buildozer.spec
          sed -i "s|\$ANDROID_HOME|$ANDROID_HOME|g" buildozer.spec
          
          # Verify the file was created correctly
          echo "=== buildozer.spec contents ==="
          cat buildozer.spec
          echo "=== File size ==="
          ls -la buildozer.spec
          
          # Initialize the environment
          buildozer android update || true
