name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-dev \
            build-essential \
            openjdk-17-jdk \
            zlib1g-dev \
            libncurses5-dev \
            libgdbm-dev \
            libnss3-dev \
            libssl-dev \
            libsqlite3-dev \
            libreadline-dev \
            libffi-dev \
            libbz2-dev \
            unzip \
            zip \
            wget

          sudo apt-get install -y openjdk-11-jdk
          sudo update-java-alternatives --set java-1.11.0-openjdk-amd64
          echo "JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64" >> $GITHUB_ENV

      - name: Set up Android SDK
        run: |
          # Create Android SDK directory
          mkdir -p $ANDROID_HOME
          cd $ANDROID_HOME
          
          # Download and extract command line tools
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip -q commandlinetools-linux-*.zip
          rm commandlinetools-linux-*.zip
          
          # Create proper directory structure (NEW FIX)
          mkdir -p cmdline-tools/latest
          mv * cmdline-tools/latest/ 2>/dev/null || true
          
          # Set PATH for Android tools
          echo "$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/34.0.0" >> $GITHUB_PATH

      - name: Install Android components
        run: |
          # Accept licenses first
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg
          
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          
          # Install required components
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "build-tools;34.0.0" "platforms;android-34" "ndk;25b"

      - name: Verify Android tools
        run: |
          echo "Android tools:"
          ls -la $ANDROID_HOME/cmdline-tools/latest/bin/
          echo "Build tools:"
          ls -la $ANDROID_HOME/build-tools/34.0.0/
          echo "Aidl exists:"
          [ -f $ANDROID_HOME/build-tools/34.0.0/aidl ] && echo "Yes" || echo "No"

      - name: Install Buildozer
        run: |
          python -m pip install --upgrade pip
          pip install cython==0.29.36 buildozer

      - name: Configure Buildozer
        run: |
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi
          echo -e "\n[android]\nandroid.ndk_path = $ANDROID_HOME/ndk/25b" >> buildozer.spec
          echo "android.sdk_path = $ANDROID_HOME" >> buildozer.spec
          echo "android.build_tools_version = 34.0.0" >> buildozer.spec

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: app-release
          path: bin/*.apk
          retention-days: 5
