name: Build Android APK

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install Android SDK and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git zip unzip \
          openjdk-11-jdk \
          python3-pip \
          autoconf libtool pkg-config \
          zlib1g-dev libncurses-dev \
          cmake libffi-dev libssl-dev
        
        # Create Android SDK directory
        mkdir -p ~/android-sdk/cmdline-tools
        cd ~/android-sdk/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip commandlinetools-linux-9477386_latest.zip
        rm commandlinetools-linux-9477386_latest.zip
        mv cmdline-tools latest
        
        # Accept licenses and install components
        yes | ~/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
        ~/android-sdk/cmdline-tools/latest/bin/sdkmanager \
          "platform-tools" \
          "platforms;android-33" \
          "build-tools;33.0.0" \
          "ndk;25.1.8937393"
        
        # Set environment variables
        echo "export ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
        echo "export PATH=$PATH:$HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools" >> $GITHUB_ENV
        
        pip install buildozer==1.5.0 cython virtualenv
        
    - name: Update buildozer.spec
      run: |
        # Remove problematic entries
        awk '!/android.allow_backup =/' buildozer.spec > temp && mv temp buildozer.spec
        awk '!/android.arch =/' buildozer.spec > temp && mv temp buildozer.spec
        
        # Add correct configurations
        echo "android.allow_backup = True" >> buildozer.spec
        echo "android.archs = armeabi-v7a" >> buildozer.spec
        echo "android.sdk_path = $HOME/android-sdk" >> buildozer.spec
        echo "android.ndk_path = $HOME/android-sdk/ndk/25.1.8937393" >> buildozer.spec
        echo "android.accept_sdk_license = True" >> buildozer.spec
        
    - name: Build APK
      run: |
        # Clean previous builds
        rm -rf .buildozer || true
        
        # Build with debug output
        buildozer -v android debug
        
        # Verify APK was created
        ls -la bin/
        if [ ! -f bin/*.apk ]; then
          echo "APK not found! Build failed."
          cat .buildozer/android/platform/build-*/build.out
          exit 1
        fi
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: calculator-app
        path: bin/*.apk
