name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-dev \
            build-essential \
            openjdk-17-jdk \
            zlib1g-dev \
            libncurses5-dev \
            libgdbm-dev \
            libnss3-dev \
            libssl-dev \
            libsqlite3-dev \
            libreadline-dev \
            libffi-dev \
            libbz2-dev \
            unzip \
            zip \
            wget

          # Install Java 11 alongside Java 17 for Android SDK compatibility
          sudo apt-get install -y openjdk-11-jdk
          sudo update-java-alternatives --set java-1.11.0-openjdk-amd64
          echo "JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64" >> $GITHUB_ENV

      - name: Set up Android SDK
        run: |
          mkdir -p $ANDROID_HOME
          cd $ANDROID_HOME
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip -q commandlinetools-linux-*.zip
          rm commandlinetools-linux-*.zip
          # Correct directory structure for cmdline-tools
          mkdir -p cmdline-tools/latest
          mv tools/* cmdline-tools/latest/
          rm -rf tools
          echo "$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/34.0.0" >> $GITHUB_PATH

      - name: Install Android components
        run: |
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "platform-tools"
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "build-tools;34.0.0"
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "platforms;android-34"
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "ndk;25b"
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Verify Android tools
        run: |
          echo "Android tools:"
          ls $ANDROID_HOME/build-tools/34.0.0/
          echo "Aidl path:"
          ls $ANDROID_HOME/build-tools/34.0.0/aidl

      - name: Install Buildozer dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cython==0.29.36 buildozer

      - name: Configure Buildozer
        run: |
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi
          echo -e "\n[android]\nandroid.ndk_path = $ANDROID_HOME/ndk/25b" >> buildozer.spec
          echo "android.sdk_path = $ANDROID_HOME" >> buildozer.spec
          echo "android.build_tools_version = 34.0.0" >> buildozer.spec

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: app-release
          path: bin/*.apk
          retention-days: 5
