name: Build Android APK

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-8-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses-dev cmake libffi-dev libssl-dev
        pip install buildozer cython virtualenv
        
    - name: Fix buildozer.spec duplicates
      run: |
        # Remove duplicate android.allow_backup entries
        awk '!/android.allow_backup =/' buildozer.spec > temp && mv temp buildozer.spec
        # Add single instance at the end
        echo "android.allow_backup = True" >> buildozer.spec
        
    - name: Build APK
      run: |
        buildozer -v android debug
        ls -la bin/
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: calculator-app
        path: bin/*.apk
