name: Build Android APK

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04  # Using LTS version for better compatibility
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-8-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses-dev cmake libffi-dev libssl-dev
        pip install buildozer==1.5.0 cython virtualenv
        
    - name: Build APK
      run: |
        buildozer -v android debug
        ls -la bin/
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: calculator-app
        path: bin/*.apk
